/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const genBlock = (id, label, items) => ({
	type: 'category',
	label,
	collapsible: false,
	link: {
		type: 'doc',
		id
	},
	items
});

const genCategory = (id, label, description = undefined) => ({
	type: 'category',
	label,
	link: {
		type: 'generated-index',
		title: `${label} Overview`,
		description,
		slug: id
	},
	items: [
		{
			type: 'autogenerated',
			dirName: id
		}
	]
});

module.exports = {
	tutorialSidebar: [
		'index',

		genBlock('application/index', 'Telestion Application (Java)', [
			genCategory(
				'application/concepts',
				'Concepts',
				'These are the core concepts that you need to know to get started with backend application development in the Telestion ecosystem.'
			),
			genCategory(
				'application/tutorials',
				'Tutorials',
				'These tutorials cover everything you need to know to build the Application side of the Telestion ecosystem.'
			),
			genCategory('application/guides', 'Guides'),
			genCategory('application/references', 'References'),
			{
				type: 'link',
				label: 'API Reference',
				href: 'https://javadoc.io/doc/de.wuespace.telestion/'
			}
		]),

		genBlock('client/index', 'Telestion Client (React / TS)', [
			genCategory(
				'client/concepts',
				'Concepts',
				'These are the core concepts that you need to know to get started with frontend client development in the Telestion ecosystem.'
			),
			genCategory(
				'client/tutorials',
				'Tutorials',
				'These tutorials cover everything you need to know to build web clients for the Telestion Ecosystem using the telestion-client library APIs.'
			),
			genCategory('client/guides', 'Guides'),
			genCategory('client/references', 'References'),
			{
				type: 'link',
				label: 'API Reference',
				href: 'https://wuespace.github.io/telestion-client/'
			}
		]),

		{
			type: 'category',
			label: 'Internal Documentation',
			items: [
				{
					type: 'autogenerated',
					dirName: 'internal'
				}
			]
		}

		// {
		//   type: 'autogenerated',
		//   dirName: '.'
		// }
	]

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
