/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const genBlock = (id, label, items) => ({
	type: 'category',
	label,
	collapsible: false,
	link: {
		type: 'doc',
		id
	},
	items
});

const genCategory = (
	id,
	label,
	description = undefined,
	categoryOptions = {}
) => ({
	type: 'category',
	label,
	link: {
		type: 'generated-index',
		title: `${label} Overview`,
		description,
		slug: id
	},
	items: [
		{
			type: 'autogenerated',
			dirName: id
		}
	],
	...categoryOptions
});

module.exports = {
	docs: [
		'index',
		'vertx-based-telestion-deprecation',
		genCategory(
			'common-concepts',
			'Common Concepts',
			'These concepts are important for everyone working with the Telestion Ecosystem to know about.',
			{
				collapsible: false
			}
		)
	],
	internal: [
		'internal/index',
		genCategory(
			'internal/concepts',
			'Concepts',
			'Core concepts for Telestion Contributors'
		),
		genCategory(
			'internal/tutorials',
			'Tutorials',
			'These tutorials cover everything you need to know to contribute to the Telestion Ecosystem'
		),
		genCategory('internal/guides', 'Guides'),
		genCategory('internal/references', 'References')
	],
	application: [
		'application/index',
		genCategory(
			'application/concepts',
			'Concepts',
			'These are the core concepts that you need to know to get started with backend application development in the Telestion ecosystem.'
		),
		genCategory(
			'application/tutorials',
			'Tutorials',
			'These tutorials cover everything you need to know to build the Application side of the Telestion ecosystem.'
		),
		genCategory('application/guides', 'Guides'),
		genCategory('application/references', 'References'),
		{
			type: 'link',
			label: 'API Reference',
			href: 'https://javadoc.io/doc/de.wuespace.telestion/'
		}
	],
	client: [
		'client/index',
		genCategory(
			'client/concepts',
			'Concepts',
			'These are the core concepts that you need to know to get started with frontend client development in the Telestion ecosystem.'
		),
		genCategory(
			'client/tutorials',
			'Tutorials',
			'These tutorials cover everything you need to know to build web clients for the Telestion Ecosystem using the telestion-client library APIs.'
		),
		genCategory('client/guides', 'Guides'),
		genCategory('client/references', 'References'),
		{
			type: 'link',
			label: 'API Reference',
			href: 'https://wuespace.github.io/telestion-client/'
		}
	]
};
